# Generated by Django 4.1.7 on 2023-03-25 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_category_category_image_photographer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photographer',
            new_name='Categorydetails',
        ),
    ]
