# Generated by Django 4.1.7 on 2023-03-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('category_image', models.ImageField(upload_to='', verbose_name=models.ImageField(default='', upload_to='images/'))),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
    ]
