# Generated by Django 4.1.4 on 2023-03-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_photographer_categorydetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='categorydetails',
            name='slug',
        ),
        migrations.AlterField(
            model_name='categorydetails',
            name='category',
            field=models.CharField(choices=[('Photography', 'Photography'), ('Beauty care', 'Beauty care'), ('Occesion', 'Occesion')], max_length=100),
        ),
        migrations.AlterField(
            model_name='categorydetails',
            name='max_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='categorydetails',
            name='min_price',
            field=models.IntegerField(),
        ),
    ]
