# Generated by Django 4.1.4 on 2023-04-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_imagetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorydetails',
            name='image1',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='categorydetails',
            name='image2',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='categorydetails',
            name='image3',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='categorydetails',
            name='image4',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='Imagetable',
        ),
    ]
