# Generated by Django 4.1.4 on 2023-04-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_categorydetails_image1_categorydetails_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorydetails',
            name='days',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='categorydetails',
            name='services',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='categorydetails',
            name='timing',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
