# Generated by Django 4.1.4 on 2023-04-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_categorydetails_days_categorydetails_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydetails',
            name='category',
            field=models.CharField(choices=[('Photography', 'Photography'), ('Beauty care', 'Beauty care'), ('Occasion', 'Occasion')], max_length=100),
        ),
    ]
