# Generated by Django 4.1.4 on 2023-04-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_categorydetails_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorydetails',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
