# Generated by Django 4.1.4 on 2023-04-29 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_vendorregistration_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorydetails',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.vendorregistration'),
        ),
    ]
