# Generated by Django 4.1.4 on 2023-04-29 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_categorydetails_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydetails',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vendorregistration'),
        ),
    ]
